# Generated by Django 3.2.25 on 2024-06-09 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pm_api', '0002_pricehistory_product_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_wishlist_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
